question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "Without enchantments, which pickaxe in minecraft mines blocks the quickest.",
     "correct_answer": "Golden ", "incorrect_answers": ["Diamond", "Iron", "Obsidian"]},
    {"type": "multiple", "difficulty": "easy", "category": "Entertainment: Cartoon &amp; Animations",
     "question": "Which of these characters from &quot;SpongeBob SquarePants&quot; is not a squid?",
     "correct_answer": "Gary", "incorrect_answers": ["Orvillie", "Squidward", "Squidette"]},
    {"type": "multiple", "difficulty": "hard", "category": "History",
     "question": "Which one of these rulers did not belong to the Habsburg dynasty?", "correct_answer": "Philip V",
     "incorrect_answers": ["Charles V", "Philip II", "Francis Joseph"]},
    {"type": "multiple", "difficulty": "easy", "category": "History",
     "question": "Who was among those killed in the 2010 Smolensk, Russia plane crash tragedy?",
     "correct_answer": "The Polish President",
     "incorrect_answers": ["Pope John Paul II", "Bang-Ding Ow", "Albert Putin"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "According to scholarly estimates, what percentage of the world population at the time died due"
                 " to Tamerlane&#039;s conquests?",
     "correct_answer": "5%", "incorrect_answers": ["1%", "3%", "&lt;1%"]},
    {"type": "boolean", "difficulty": "medium", "category": "History",
     "question": "Brezhnev was the 5th leader of the USSR.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "multiple", "difficulty": "medium", "category": "History",
     "question": "One of the deadliest pandemics, the &quot;Spanish Flu&quot;, killed off what "
                 "percentage of the human world population at the time?",
     "correct_answer": "3 to 6 percent",
     "incorrect_answers": ["6 to 10 percent", "1 to 3 percent", "less than 1 percent"]},
    {"type": "multiple", "difficulty": "medium", "category": "General Knowledge",
     "question": "What did the Spanish autonomous community of Catalonia ban in 2010, that took effect in 2012?",
     "correct_answer": "Bullfighting", "incorrect_answers": ["Fiestas", "Flamenco", "Mariachi"]},
    {"type": "multiple", "difficulty": "medium", "category": "Geography",
     "question": "What is the capital of the State of Washington, United States?", "correct_answer": "Olympia",
     "incorrect_answers": ["Washington D.C.", "Seattle", "Yukon"]},
    {"type": "multiple", "difficulty": "medium", "category": "Entertainment: Video Games",
     "question": "In the 2002 video game &quot;Kingdom Hearts&quot;, how many playable worlds were there?",
     "correct_answer": "14", "incorrect_answers": ["13", "16", "11"]}]
